CREATE DATABASE teachersportal_db;

USE teachersportal_db;

CREATE TABLE tbl_genders
(
	gender_id BIGINT NOT NULL AUTO_INCREMENT,
	gender VARCHAR(45) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(gender_id)
);

CREATE TABLE tbl_positions
(
	position_id BIGINT NOT NULL AUTO_INCREMENT,
	`position` VARCHAR(45) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(position_id)
);

CREATE TABLE tbl_users
(
	user_id BIGINT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(45) NOT NULL,
	middle_name VARCHAR(45) DEFAULT NULL,
	last_name VARCHAR(45) NOT NULL,
	gender_id BIGINT NOT NULL,
	age INT NOT NULL,
	address VARCHAR(45) NOT NULL,
	contact_number VARCHAR(45) DEFAULT NULL,
	email_address VARCHAR(45) NOT NULL,
	`password` VARCHAR(45) NOT NULL,
	position_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(user_id),
	FOREIGN KEY(gender_id) REFERENCES tbl_genders(gender_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(position_id) REFERENCES tbl_positions(position_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE tbl_students
(
	student_id BIGINT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(45) NOT NULL,
	middle_name VARCHAR(45) DEFAULT NULL,
	last_name VARCHAR(45) NOT NULL,
	gender_id BIGINT NOT NULL,
	age INT NOT NULL,
	address VARCHAR(45) NOT NULL,
	contact_number VARCHAR(45) DEFAULT NULL,
	email_address VARCHAR(45) NOT NULL,
	user_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(student_id),
	FOREIGN KEY(gender_id) REFERENCES tbl_genders(gender_id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(user_id) REFERENCES tbl_users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);